services:
  # RAG Service (Private - Internal only)
  - type: pserv
    name: rag-service
    runtime: docker
    repo: https://github.com/cswylie/Strum
    dockerfilePath: ./rag_service/Dockerfile
    dockerContext: ./rag_service
    disk:
      name: rag-data
      mountPath: /app/data
      sizeGB: 10
    envVars:
      - key: OLLAMA_MODELS
        value: /app/ollama-models
    # Private service - only accessible by other services
    
  # Backend Service (Public - Exposed to internet)
  - type: web
    name: strum-backend
    runtime: docker
    repo: https://github.com/cswylie/Strum
    dockerfilePath: ./strum_service/Dockerfile
    dockerContext: ./strum_service
    envVars:
      - key: RAG_SERVICE_URL
        value: http://rag-service:8000/query
      - key: PORT
        value: 3000
    # This will be accessible via HTTPS at your-service-name.onrender.com

# Persistent storage for RAG service
disks:
  - name: rag-data
    sizeGB: 10