version: "3.8"
services:
  backend:
    build: ./strum_service
    container_name: strum_backend
    ports:
      - "3000:3000"  # Expose Node API to host
    depends_on:
      - rag_service
    environment:
      # Let Node know where the Python API is
      - RAG_SERVICE_URL=http://rag_service:8000/query
    networks:
      - strum_network

  rag_service:
    build: ./rag_service
    container_name: rag_service
    ports: [] # internal only, we don't need to expose it
    volumes:
      - ./rag_service/data:/app/data  # FAISS & docs, bind volumes
      - ./rag_service/ollama-models:/app/ollama-models  # Persist Mistral model
    networks:
      - strum_network

networks:
  strum_network:
    driver: bridge
